// Hosting a server inside the desktop app — the process half of ADR 0005.
//
// The *policy* — which ports to prefer, when a set of component states counts
// as usable, what each install step is called — lives in shared/hosting.ts,
// in TypeScript, where it is unit-tested. This module is deliberately the
// dumb half: it unpacks files, spawns processes, reports what happened, and
// decides nothing it doesn't have to. When one of them dies, the frontend is
// told which one and why; what that *means* is TypeScript's problem.
//
// Everything here is std plus what Cargo.toml already carried. No new crates:
// secrets are generated in the webview (crypto.getRandomValues) and arrive as
// arguments, health is judged by the frontend polling /ready over HTTP, and
// process trees are torn down with the tools each component itself ships
// (pg_ctl for Postgres, plain kill for the single-process Go and Node ones).

use serde::Serialize;
use std::collections::HashMap;
use std::io::Write;
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;
use tauri::{AppHandle, Emitter, Manager};

/// Child processes, keyed by component id. One instance of hosting per app.
pub struct HostProcesses(pub Mutex<HashMap<String, Child>>);

#[derive(Clone, Serialize)]
pub struct ComponentReport {
    pub id: String,
    pub state: String,
    pub port: Option<u16>,
    pub error: Option<String>,
}

#[derive(Clone, Serialize)]
pub struct HostReport {
    pub installed: bool,
    pub components: Vec<ComponentReport>,
    /// Where the app answers once running — what the frontend connects to.
    pub url: Option<String>,
}

#[derive(serde::Deserialize)]
pub struct HostSecrets {
    /// scram password for the bundled Postgres. Generated by the frontend,
    /// stored in the OS keychain by the frontend, never written to disk here
    /// except the pwfile initdb consumes, which is deleted immediately after.
    pub db_password: String,
    pub jwt_secret: String,
    pub matrix_shared_secret: String,
}

#[derive(serde::Deserialize)]
pub struct PortPlan {
    /// Candidates in preference order, per component — computed by
    /// shared/hosting.ts portCandidates(), so the policy stays in one place.
    pub postgres: Vec<u16>,
    pub matrix: Vec<u16>,
    pub ipfs: Vec<u16>,
    pub app: Vec<u16>,
}

// ---------------------------------------------------------------- filesystem

/// Where the hosted server's mutable state lives: databases, IPFS repo,
/// rendered configs. Survives app updates; removed only by an uninstall that
/// asked first.
fn data_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let base = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("no app data dir: {e}"))?;
    Ok(base.join("host"))
}

/// Where the bundled, read-only components were installed with the app:
/// resources/host/<postgres|dendrite|kubo|node|app>. Empty in a dev build.
fn bundle_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let resources = app
        .path()
        .resource_dir()
        .map_err(|e| format!("no resource dir: {e}"))?;
    Ok(resources.join("host"))
}

fn exe(name: &str) -> String {
    if cfg!(windows) {
        format!("{name}.exe")
    } else {
        name.to_string()
    }
}

fn postgres_bin(app: &AppHandle, tool: &str) -> Result<PathBuf, String> {
    Ok(bundle_dir(app)?.join("postgres").join("bin").join(exe(tool)))
}

/// The bundle is what turns a client install into a possible host. A dev
/// build ships without one, and the truthful answer there is "this build
/// can't host", not a spawn error three steps later.
fn bundle_present(app: &AppHandle) -> bool {
    postgres_bin(app, "initdb").map(|p| p.exists()).unwrap_or(false)
        && bundle_dir(app)
            .map(|d| d.join(exe("dendrite")).exists() && d.join(exe("kubo")).exists() && d.join(exe("node")).exists())
            .unwrap_or(false)
}

fn installed(app: &AppHandle) -> bool {
    data_dir(app)
        .map(|d| d.join("pg").join("PG_VERSION").exists())
        .unwrap_or(false)
}

// -------------------------------------------------------------------- events

fn emit_step(app: &AppHandle, id: &str) {
    let _ = app.emit("host-install-step", id);
}

fn emit_state(app: &AppHandle, report: &HostReport) {
    let _ = app.emit("host-state", report.clone());
}

// --------------------------------------------------------------------- ports

/// First candidate that binds on loopback. Binding and releasing is the only
/// honest availability test; anything else races less and lies more.
fn pick_port(candidates: &[u16]) -> Result<u16, String> {
    for &port in candidates {
        if TcpListener::bind(("127.0.0.1", port)).is_ok() {
            return Ok(port);
        }
    }
    Err("no free port in range".to_string())
}

// ----------------------------------------------------------------- processes

/// Spawn with stdout/stderr captured to a per-component log file, because a
/// crashing homeserver with no log is a support thread that never resolves.
fn spawn_logged(
    mut command: Command,
    log_path: &Path,
) -> Result<Child, String> {
    let log = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(log_path)
        .map_err(|e| format!("couldn't open log {}: {e}", log_path.display()))?;
    let log_err = log.try_clone().map_err(|e| e.to_string())?;
    command
        .stdin(Stdio::null())
        .stdout(Stdio::from(log))
        .stderr(Stdio::from(log_err));

    // On Windows, a console subsystem child would flash a terminal window
    // every launch. CREATE_NO_WINDOW keeps the processes as invisible as a
    // service should be.
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }

    command.spawn().map_err(|e| e.to_string())
}

fn run_to_completion(mut command: Command, what: &str) -> Result<(), String> {
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
    let output = command
        .output()
        .map_err(|e| format!("{what}: couldn't run: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("{what}: {}", stderr.trim().chars().take(400).collect::<String>()));
    }
    Ok(())
}

/// Wait for something to accept a TCP connection. Readiness beyond this —
/// "does /ready say ready" — is the frontend's job, over HTTP, where the
/// policy for what counts lives.
fn wait_for_port(port: u16, timeout_secs: u64) -> bool {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    while std::time::Instant::now() < deadline {
        if std::net::TcpStream::connect(("127.0.0.1", port)).is_ok() {
            return true;
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
    }
    false
}

// ------------------------------------------------------------------- install

/// One-time setup: database cluster, homeserver identity, IPFS repo.
///
/// Steps are emitted by id as they begin; the labels live in
/// shared/hosting.ts INSTALL_STEPS, so what a person reads is tested policy
/// and what happens is this.
#[tauri::command]
pub async fn host_install(
    app: AppHandle,
    secrets: HostSecrets,
) -> Result<(), String> {
    if !bundle_present(&app) {
        return Err(
            "This build ships without server components — install a release build to host."
                .to_string(),
        );
    }
    if installed(&app) {
        return Ok(()); // Idempotent: an interrupted install can be retried.
    }

    let data = data_dir(&app)?;
    let logs = data.join("logs");

    emit_step(&app, "unpack");
    std::fs::create_dir_all(&logs).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(data.join("ipfs")).map_err(|e| e.to_string())?;

    // -- database ------------------------------------------------------------
    emit_step(&app, "database");

    // initdb reads the superuser password from a file, which exists for the
    // seconds initdb runs and is removed before anything else happens.
    let pwfile = data.join("pwfile");
    std::fs::write(&pwfile, &secrets.db_password).map_err(|e| e.to_string())?;

    let result = run_to_completion(
        {
            let mut c = Command::new(postgres_bin(&app, "initdb")?);
            c.arg("-D")
                .arg(data.join("pg"))
                .arg("-U")
                .arg("sovrgn")
                .arg("--auth=scram-sha-256")
                .arg("--pwfile")
                .arg(&pwfile)
                .arg("-E")
                .arg("UTF8");
            c
        },
        "initdb",
    );
    let _ = std::fs::remove_file(&pwfile);
    result?;

    // Unix sockets go in the data dir rather than /var/run, which needs no
    // privileges and exists on every platform that has sockets at all.
    let conf = data.join("pg").join("postgresql.conf");
    let mut extra = String::from("\n# SOVRGNnet hosted-server settings\nlisten_addresses = '127.0.0.1'\n");
    if !cfg!(windows) {
        extra.push_str(&format!(
            "unix_socket_directories = '{}'\n",
            data.join("pg").display()
        ));
    }
    std::fs::OpenOptions::new()
        .append(true)
        .open(&conf)
        .and_then(|mut f| f.write_all(extra.as_bytes()))
        .map_err(|e| format!("couldn't extend postgresql.conf: {e}"))?;

    // -- homeserver identity -------------------------------------------------
    emit_step(&app, "homeserver");

    // The signing key is this server's permanent identity on the Matrix
    // network. generate-keys ships alongside dendrite from the same build.
    run_to_completion(
        {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("generate-keys")));
            c.arg("--private-key")
                .arg(data.join("matrix_key.pem"));
            c
        },
        "generate-keys",
    )?;

    // -- file storage --------------------------------------------------------
    emit_step(&app, "storage");

    run_to_completion(
        {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("init").env("IPFS_PATH", data.join("ipfs"));
            c
        },
        "ipfs init",
    )?;

    // -- secrets -------------------------------------------------------------
    // Nothing to write: they came from the keychain via the frontend and go
    // into process environments at start. The step exists so the person sees
    // it happen rather than wondering what "keys" meant.
    emit_step(&app, "secrets");

    Ok(())
}

// --------------------------------------------------------------------- start

fn render_dendrite_config(
    app: &AppHandle,
    data: &Path,
    pg_port: u16,
    secrets: &HostSecrets,
) -> Result<PathBuf, String> {
    let template_path = bundle_dir(app)?.join("dendrite.yaml.template");
    let template = std::fs::read_to_string(&template_path)
        .map_err(|e| format!("couldn't read dendrite template: {e}"))?;

    let database_url = format!(
        "postgresql://sovrgn:{}@127.0.0.1:{}/dendrite?sslmode=disable",
        secrets.db_password, pg_port
    );

    let rendered = template
        .replace("__MATRIX_SERVER_NAME__", "sovrgn.host")
        .replace("__MATRIX_SHARED_SECRET__", &secrets.matrix_shared_secret)
        .replace("__DENDRITE_DISABLE_FEDERATION__", "true")
        .replace("__DENDRITE_DATABASE_URL__", &database_url);

    // The same guard the install scripts apply: a placeholder that survives
    // rendering means the template grew a field this code doesn't know.
    for line in rendered.lines() {
        let code = line.trim_start();
        if !code.starts_with('#') && code.contains("__") && code.contains("__MATRIX") {
            return Err(format!("unfilled placeholder in dendrite template: {code}"));
        }
    }

    // The bundled template points private_key at /etc/dendrite; here it lives
    // in the data dir. Rewritten rather than templated so the production
    // template stays exactly what production uses.
    let rendered = rendered.replace(
        "/etc/dendrite/matrix_key.pem",
        &data.join("matrix_key.pem").display().to_string(),
    );

    // The listen port is a CLI flag at spawn, not a config field — the port
    // is picked fresh each start and the config shouldn't pretend otherwise.
    let path = data.join("dendrite.yaml");
    std::fs::write(&path, rendered).map_err(|e| e.to_string())?;
    Ok(path)
}

/// Start every component. Returns the final report; the same report is also
/// emitted as an event so the UI can render without racing the invoke.
#[tauri::command]
pub async fn host_start(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
    secrets: HostSecrets,
    ports: PortPlan,
) -> Result<HostReport, String> {
    if !installed(&app) {
        return Err("Nothing is installed to start.".to_string());
    }

    let data = data_dir(&app)?;
    let logs = data.join("logs");
    std::fs::create_dir_all(&logs).map_err(|e| e.to_string())?;

    let mut components: Vec<ComponentReport> = Vec::new();
    let mut fail = |components: &mut Vec<ComponentReport>, id: &str, error: String| {
        components.push(ComponentReport {
            id: id.to_string(),
            state: "failed".to_string(),
            port: None,
            error: Some(error),
        });
    };

    // -- postgres ------------------------------------------------------------
    let pg_port = pick_port(&ports.postgres)?;
    {
        let mut c = Command::new(postgres_bin(&app, "postgres")?);
        c.arg("-D")
            .arg(data.join("pg"))
            .arg("-p")
            .arg(pg_port.to_string());
        match spawn_logged(c, &logs.join("postgres.log")) {
            Ok(child) => {
                processes.0.lock().unwrap().insert("postgres".into(), child);
                if wait_for_port(pg_port, 30) {
                    components.push(ComponentReport {
                        id: "postgres".into(),
                        state: "running".into(),
                        port: Some(pg_port),
                        error: None,
                    });
                } else {
                    fail(&mut components, "postgres", "didn't accept connections within 30s".into());
                }
            }
            Err(e) => fail(&mut components, "postgres", e),
        }
    }

    // The two databases, created if they don't exist. createdb failing
    // because the database exists is the ordinary second launch, not an
    // error; any other failure is real.
    if components.iter().any(|c| c.id == "postgres" && c.state == "running") {
        for db in ["sovrgnnet", "dendrite"] {
            let mut c = Command::new(postgres_bin(&app, "createdb")?);
            c.arg("-h")
                .arg("127.0.0.1")
                .arg("-p")
                .arg(pg_port.to_string())
                .arg("-U")
                .arg("sovrgn")
                .arg(db)
                .env("PGPASSWORD", &secrets.db_password);
            if let Err(e) = run_to_completion(c, &format!("createdb {db}")) {
                if !e.contains("already exists") {
                    return Err(e);
                }
            }
        }
    }

    // -- dendrite ------------------------------------------------------------
    let matrix_port = pick_port(&ports.matrix)?;
    match render_dendrite_config(&app, &data, pg_port, &secrets) {
        Ok(config) => {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("dendrite")));
            c.arg("--config")
                .arg(&config)
                .arg("--http-bind-address")
                .arg(format!("127.0.0.1:{matrix_port}"));
            match spawn_logged(c, &logs.join("dendrite.log")) {
                Ok(child) => {
                    processes.0.lock().unwrap().insert("matrix".into(), child);
                    components.push(ComponentReport {
                        id: "matrix".into(),
                        state: if wait_for_port(matrix_port, 60) { "running" } else { "starting" }.into(),
                        port: Some(matrix_port),
                        error: None,
                    });
                }
                Err(e) => fail(&mut components, "matrix", e),
            }
        }
        Err(e) => fail(&mut components, "matrix", e),
    }

    // -- kubo ----------------------------------------------------------------
    let ipfs_port = pick_port(&ports.ipfs)?;
    {
        // The repo's addresses are rewritten each start, because the port is
        // picked each start. Kubo reads them from its config, not flags.
        for (key, value) in [
            ("Addresses.API", format!("\"/ip4/127.0.0.1/tcp/{ipfs_port}\"")),
            ("Addresses.Gateway", format!("\"/ip4/127.0.0.1/tcp/{}\"", ipfs_port + 1)),
        ] {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("config").arg("--json").arg(key).arg(&value).env("IPFS_PATH", data.join("ipfs"));
            if let Err(e) = run_to_completion(c, &format!("ipfs config {key}")) {
                fail(&mut components, "ipfs", e);
                break;
            }
        }
        if !components.iter().any(|c| c.id == "ipfs") {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("daemon").env("IPFS_PATH", data.join("ipfs"));
            match spawn_logged(c, &logs.join("ipfs.log")) {
                Ok(child) => {
                    processes.0.lock().unwrap().insert("ipfs".into(), child);
                    components.push(ComponentReport {
                        id: "ipfs".into(),
                        state: "starting".into(), // fine to be late; chat doesn't wait for files
                        port: Some(ipfs_port),
                        error: None,
                    });
                }
                Err(e) => fail(&mut components, "ipfs", e),
            }
        }
    }

    // -- app -----------------------------------------------------------------
    let app_port = pick_port(&ports.app)?;
    {
        let bundle = bundle_dir(&app)?;
        let mut c = Command::new(bundle.join(exe("node")));
        c.arg(bundle.join("app").join("index.mjs"))
            .current_dir(bundle.join("app"))
            .env("NODE_ENV", "production")
            .env("PORT", app_port.to_string())
            .env(
                "DATABASE_URL",
                format!(
                    "postgresql://sovrgn:{}@127.0.0.1:{}/sovrgnnet",
                    secrets.db_password, pg_port
                ),
            )
            .env("JWT_SECRET", &secrets.jwt_secret)
            .env("MATRIX_SHARED_SECRET", &secrets.matrix_shared_secret)
            .env("MATRIX_SERVER_NAME", "sovrgn.host")
            .env("MATRIX_HOMESERVER_URL", format!("http://127.0.0.1:{matrix_port}"))
            .env("IPFS_API_URL", format!("http://127.0.0.1:{ipfs_port}"))
            .env("INSTANCE_NAME", "My computer")
            .env("INSTANCE_JOIN_POLICY", "invite")
            .env("SOVRGNNET_ACCESS_MODE", "lan");
        // First boot applies migrations; the step is announced so the pause
        // reads as work rather than a hang.
        emit_step(&app, "migrate");
        match spawn_logged(c, &logs.join("app.log")) {
            Ok(child) => {
                emit_step(&app, "start");
                processes.0.lock().unwrap().insert("app".into(), child);
                components.push(ComponentReport {
                    id: "app".into(),
                    state: if wait_for_port(app_port, 90) { "running" } else { "starting" }.into(),
                    port: Some(app_port),
                    error: None,
                });
            }
            Err(e) => fail(&mut components, "app", e),
        }
    }

    let url = components
        .iter()
        .find(|c| c.id == "app" && c.state == "running")
        .and_then(|c| c.port)
        .map(|p| format!("http://127.0.0.1:{p}"));

    let report = HostReport {
        installed: true,
        components,
        url,
    };
    emit_state(&app, &report);
    Ok(report)
}

// ---------------------------------------------------------------------- stop

/// Stop everything, most-dependent first. Postgres goes through pg_ctl so it
/// checkpoints instead of recovering on next start; the single-process Go and
/// Node components are killed, which their databases are built to survive.
#[tauri::command]
pub async fn host_stop(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
) -> Result<(), String> {
    stop_all(&app, &processes);
    Ok(())
}

pub fn stop_all(app: &AppHandle, processes: &HostProcesses) {
    let mut map = processes.0.lock().unwrap();

    for id in ["app", "ipfs", "matrix"] {
        if let Some(mut child) = map.remove(id) {
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    if let Some(mut child) = map.remove("postgres") {
        let stopped = data_dir(app)
            .and_then(|data| {
                run_to_completion(
                    {
                        let mut c = Command::new(postgres_bin(app, "pg_ctl")?);
                        c.arg("stop").arg("-D").arg(data.join("pg")).arg("-m").arg("fast");
                        c
                    },
                    "pg_ctl stop",
                )
            })
            .is_ok();
        if !stopped {
            let _ = child.kill();
        }
        let _ = child.wait();
    }
}

// --------------------------------------------------------------------- state

/// The current picture: what's installed, what's running, what died.
///
/// A child that exited is reported as failed with whatever exit status it
/// left, which is how the frontend learns about a crash between polls.
#[tauri::command]
pub async fn host_state(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
) -> Result<HostReport, String> {
    let mut components = Vec::new();
    let mut map = processes.0.lock().unwrap();

    for (id, child) in map.iter_mut() {
        let state = match child.try_wait() {
            Ok(None) => ("running".to_string(), None),
            Ok(Some(status)) => ("failed".to_string(), Some(format!("exited: {status}"))),
            Err(e) => ("failed".to_string(), Some(e.to_string())),
        };
        components.push(ComponentReport {
            id: id.clone(),
            state: state.0,
            port: None,
            error: state.1,
        });
    }

    Ok(HostReport {
        installed: installed(&app),
        components,
        url: None,
    })
}

/// Whether this build can host at all, and whether it already does.
#[tauri::command]
pub async fn host_available(app: AppHandle) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({
        "bundled": bundle_present(&app),
        "installed": installed(&app),
    }))
}
