// Hosting a server inside the desktop app — the process half of ADR 0005.
//
// The *policy* — which ports to prefer, when a set of component states counts
// as usable, what each install step is called — lives in shared/hosting.ts,
// in TypeScript, where it is unit-tested. This module is deliberately the
// dumb half: it unpacks files, spawns processes, reports what happened, and
// decides nothing it doesn't have to. When one of them dies, the frontend is
// told which one and why; what that *means* is TypeScript's problem.
//
// Everything here is std plus what Cargo.toml already carried. No new crates:
// secrets are generated in the webview (crypto.getRandomValues) and arrive as
// arguments, health is judged by the frontend polling /ready over HTTP, and
// process trees are torn down with the tools each component itself ships
// (pg_ctl for Postgres, plain kill for the single-process Go and Node ones).

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::io::{BufRead, BufReader, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;
use tauri::{AppHandle, Emitter, Manager};

/// Child processes, keyed by component id. One instance of hosting per app.
pub struct HostProcesses(pub Mutex<HashMap<String, Child>>);

/// Why voice is deliberately not running, when it isn't.
///
/// host_state rebuilds its component list from live child processes, and a
/// component that was never spawned has no child — so a skipped SFU would
/// appear in the start report once and then vanish from every poll, leaving
/// the panel unable to say why there's no voice. A module static rather than
/// a field on HostProcesses because hosting is a singleton per app and the
/// reason has exactly one writer (host_start) and one reader (host_state).
static VOICE_OFF_REASON: Mutex<Option<String>> = Mutex::new(None);

/// The public address the quick tunnel was assigned, once cloudflared says.
///
/// Same shape and same reasoning as VOICE_OFF_REASON: one writer (the thread
/// reading cloudflared's stderr), readers in host_start and host_state, and no
/// natural home on HostProcesses because it is a fact about the tunnel rather
/// than a handle to it. Cleared by stop_all, because a stopped tunnel's old
/// hostname is precisely the kind of stale truth that gets pasted into an
/// invite.
static TUNNEL_URL: Mutex<Option<String>> = Mutex::new(None);

#[derive(Clone, Serialize)]
pub struct ComponentReport {
    pub id: String,
    pub state: String,
    pub port: Option<u16>,
    pub error: Option<String>,
}

#[derive(Clone, Serialize)]
pub struct HostReport {
    pub installed: bool,
    pub components: Vec<ComponentReport>,
    /// Where the app answers once running — what the frontend connects to.
    pub url: Option<String>,
    /// Where the rest of the world reaches it, when a tunnel is up. Distinct
    /// from `url` on purpose: the app itself is always dialled on loopback,
    /// and the public address is only ever for handing to someone else.
    pub public_url: Option<String>,
}

/// How the server is exposed — the persisted half of shared/hosting.ts's
/// `HostOptions`. Written by the frontend through `host_options_write` once
/// a person has chosen, read back on every later start so the choice
/// survives the app. Lives in the data directory as plain JSON rather than
/// the keychain, because it is a preference and not a secret, and because
/// the keychain's "host" entry is documented as carrying secrets only.
#[derive(Clone, Serialize, Deserialize)]
pub struct HostOptions {
    /// "lan" or "tunnel". A string rather than an enum so a value written by
    /// a newer frontend still deserialises here; anything unrecognised is
    /// treated as "lan", the mode with no exposure to get wrong.
    pub access: String,
}

impl HostOptions {
    fn wants_tunnel(&self) -> bool {
        self.access == "tunnel"
    }
}

#[derive(serde::Deserialize)]
pub struct HostSecrets {
    /// scram password for the bundled Postgres. Generated by the frontend,
    /// stored in the OS keychain by the frontend, never written to disk here
    /// except the pwfile initdb consumes, which is deleted immediately after.
    pub db_password: String,
    pub jwt_secret: String,
    pub matrix_shared_secret: String,
    /// This install's Matrix server name, proposed by the frontend.
    ///
    /// Generated in the webview with `crypto.getRandomValues`, like every other
    /// value in this struct — this module deliberately carries no RNG crate.
    /// Only consulted when there is no name on disk yet; see
    /// `matrix_server_name`.
    ///
    /// The token the instance requires before it will create its first
    /// account. Generated and kept by the frontend, like everything else here.
    ///
    /// Without it a desktop-hosted server refuses to bootstrap — the guard is
    /// right, and nothing was passing it, so hosting produced a server whose
    /// first account could not be created. `default` for the same reason as
    /// the field below.
    #[serde(default)]
    pub setup_token: String,
    /// `default` because keychain entries written before this field existed
    /// must still deserialize; an empty value means "an older install", which
    /// that function handles explicitly.
    #[serde(default)]
    pub matrix_server_name: String,
    /// The key pair the bundled voice SFU accepts admission tokens under —
    /// ADR 0013 as superseded. The key is an identifier (it becomes the
    /// token issuer); the secret signs admissions. Generated and kept by the
    /// frontend like everything else here. `default` for the same reason as
    /// the fields above: a keychain entry from before voice existed must
    /// still deserialize, and empty simply means voice stays off this start.
    #[serde(default)]
    pub livekit_api_key: String,
    #[serde(default)]
    pub livekit_api_secret: String,
    /// The appservice registration's two tokens — ADR 0009, mandatory since
    /// ADR 0015. as_token is what the instance would present to the
    /// homeserver; hs_token is what the homeserver presents on every event it
    /// pushes to the instance. Both rendered into appservice.yaml and handed
    /// to the app; both `default` for the usual reason, and an install whose
    /// keychain predates them is backfilled by the frontend before this
    /// struct is ever built.
    #[serde(default)]
    pub appservice_as_token: String,
    #[serde(default)]
    pub appservice_hs_token: String,
}

#[derive(serde::Deserialize)]
pub struct PortPlan {
    /// Candidates in preference order, per component — computed by
    /// shared/hosting.ts portCandidates(), so the policy stays in one place.
    pub postgres: Vec<u16>,
    pub matrix: Vec<u16>,
    pub ipfs: Vec<u16>,
    pub voice: Vec<u16>,
    pub app: Vec<u16>,
    /// The UDP range WebRTC media rides, inclusive — VOICE_UDP_RANGE in
    /// shared/hosting.ts. Fixed policy rather than picked here: UDP can't be
    /// probed by binding a TCP listener, and the number belongs in
    /// TypeScript with every other port decision.
    pub voice_udp: (u16, u16),
}

// ---------------------------------------------------------------- filesystem

/// Strip Windows' verbatim path prefix before a path reaches a child process.
///
/// Tauri's `resource_dir()` and `app_data_dir()` return canonicalised paths,
/// and on Windows canonicalisation produces the extended-length form:
/// `\\?\C:\Users\...`. That prefix is valid for the Win32 API and completely
/// fine for anything using it through Rust — which is why this is invisible
/// until a bundled program does its own path handling.
///
/// Postgres does. `initdb` locates its siblings by taking its own argv[0],
/// stripping the filename and appending `postgres.exe`, and that logic does
/// not understand `\\?\`. The failure it produces names the right file at the
/// right path and still says it cannot be found:
///
/// ```text
/// initdb: error: program "postgres" is needed by initdb but was not found in
/// the same directory as "//?/C:/Users/.../host/postgres/bin/initdb.exe"
/// ```
///
/// Which reads as a broken or incomplete bundle, and is not: every file is
/// exactly where it should be. Only the prefix is wrong.
///
/// UNC paths (`\\?\UNC\server\share`) are left alone. Removing the prefix there
/// yields `UNC\server\share`, which is not a path at all — a network install is
/// rare enough that refusing to mangle it beats a clever conversion nobody
/// tests.
fn simplified(path: PathBuf) -> PathBuf {
    if !cfg!(windows) {
        return path;
    }
    match path.to_str() {
        Some(text) => match text.strip_prefix(r"\\?\") {
            Some(rest) if !rest.starts_with("UNC\\") => PathBuf::from(rest),
            _ => path,
        },
        // Not valid UTF-8: leave it exactly as it came. A path we can't read
        // is not one to start rewriting.
        None => path,
    }
}

/// Where the hosted server's mutable state lives: databases, IPFS repo,
/// rendered configs. Survives app updates; removed only by an uninstall that
/// asked first.
fn data_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let base = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("no app data dir: {e}"))?;
    Ok(simplified(base.join("host")))
}

/// This install's Matrix server name, decided once and then permanent.
///
/// Every desktop host used to be called `sovrgn.host`. That was not cosmetic:
///
/// - `instanceId()` on the server side is a hash of `MATRIX_SERVER_NAME`, and
///   sovrgnnet.cc identity tokens are **audience-bound to the instance id**.
///   One shared name means one shared audience, so a token minted for somebody
///   on one desktop host verified successfully on *every* desktop host. That is
///   exactly the replay the audience check exists to stop, defeated for the
///   entire desktop population at once.
/// - Backup restore refuses a backup whose `matrixServerName` differs from the
///   target's, because Matrix IDs embed the server name permanently. Identical
///   names made that guard pass between two unrelated people's machines, so the
///   check that prevents a catastrophic restore was inert too.
/// - Matrix IDs and room IDs collided, so nothing downstream could tell two
///   desktop hosts apart even in principle.
///
/// ## Why this is read-or-create, and never regenerated
///
/// A Matrix server name is baked into every user ID and room ID the moment they
/// are created, and Matrix has no rename — the same constraint ADR 0012 records
/// one level up. Generating a fresh name for an install that already has a
/// Dendrite database would orphan every account and room in it: the data stays
/// on disk, addressed by a name the server no longer answers to.
///
/// So the name is written once, on the first start without one, and read
/// verbatim after that. If there is no name file but there *is* an existing
/// database, the install predates this fix and keeps `sovrgn.host` —
/// grandfathered rather than silently broken. Those installs still collide, and
/// that is recorded in the threat model rather than papered over.
fn matrix_server_name(data: &Path, proposed: &str) -> Result<String, String> {
    let path = data.join("matrix-server-name");

    if let Ok(existing) = std::fs::read_to_string(&path) {
        let name = existing.trim().to_string();
        if !name.is_empty() {
            return Ok(name);
        }
    }

    // An install from before this existed. Its Matrix IDs already say
    // sovrgn.host, and changing that would lose them.
    let legacy = data.join("dendrite").exists() || data.join("postgres").exists();
    let name = if legacy {
        "sovrgn.host".to_string()
    } else if !proposed.trim().is_empty() {
        proposed.trim().to_string()
    } else {
        // No name on disk, no existing database, and the frontend didn't offer
        // one. Refusing beats guessing: inventing a name here would either
        // reintroduce the shared one or need an RNG this module has no crate
        // for, and a wrong permanent name is not a recoverable mistake.
        return Err(
            "no Matrix server name available — the app needs to supply one before hosting"
                .to_string(),
        );
    };

    std::fs::create_dir_all(data)
        .map_err(|e| format!("couldn't create the host data dir: {e}"))?;
    // Written before anything uses it: a crash between generating and starting
    // Dendrite must not leave a database under a name we've forgotten.
    std::fs::write(&path, format!("{name}\n"))
        .map_err(|e| format!("couldn't record the server name: {e}"))?;
    Ok(name)
}

/// Where the bundled, read-only components were installed with the app:
/// resources/host/<postgres|dendrite|kubo|node|app>. Empty in a dev build.
fn bundle_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let resources = app
        .path()
        .resource_dir()
        .map_err(|e| format!("no resource dir: {e}"))?;
    Ok(simplified(resources.join("host")))
}

fn exe(name: &str) -> String {
    if cfg!(windows) {
        format!("{name}.exe")
    } else {
        name.to_string()
    }
}

fn postgres_bin(app: &AppHandle, tool: &str) -> Result<PathBuf, String> {
    Ok(bundle_dir(app)?.join("postgres").join("bin").join(exe(tool)))
}

/// The bundle is what turns a client install into a possible host. A dev
/// build ships without one, and the truthful answer there is "this build
/// can't host", not a spawn error three steps later.
fn bundle_present(app: &AppHandle) -> bool {
    // Every Postgres binary this module spawns, because checking one and
    // inferring the rest is how a build shipped without `createdb`: `initdb`
    // was present, this returned true, the offer to host appeared, and setup
    // failed partway through with a file-not-found from three steps later.
    //
    // `createdb` is no longer among them — it is missing from the upstream
    // tarball on two platforms of three, so the databases are created over a
    // connection instead.
    ["initdb", "postgres", "pg_ctl"]
        .iter()
        .all(|tool| postgres_bin(app, tool).map(|p| p.exists()).unwrap_or(false))
        && bundle_dir(app)
            .map(|d| d.join(exe("dendrite")).exists() && d.join(exe("kubo")).exists() && d.join(exe("node")).exists())
            .unwrap_or(false)
}

fn installed(app: &AppHandle) -> bool {
    data_dir(app)
        .map(|d| d.join("pg").join("PG_VERSION").exists())
        .unwrap_or(false)
}

// -------------------------------------------------------------------- events

fn emit_step(app: &AppHandle, id: &str) {
    let _ = app.emit("host-install-step", id);
}

fn emit_state(app: &AppHandle, report: &HostReport) {
    let _ = app.emit("host-state", report.clone());
}

// --------------------------------------------------------------------- ports

/// First candidate that binds on loopback. Binding and releasing is the only
/// honest availability test; anything else races less and lies more.
fn pick_port(candidates: &[u16]) -> Result<u16, String> {
    for &port in candidates {
        if TcpListener::bind(("127.0.0.1", port)).is_ok() {
            return Ok(port);
        }
    }
    Err("no free port in range".to_string())
}

// ----------------------------------------------------------------- processes

/// Spawn with stdout/stderr captured to a per-component log file, because a
/// crashing homeserver with no log is a support thread that never resolves.
fn spawn_logged(
    mut command: Command,
    log_path: &Path,
) -> Result<Child, String> {
    let log = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(log_path)
        .map_err(|e| format!("couldn't open log {}: {e}", log_path.display()))?;
    let log_err = log.try_clone().map_err(|e| e.to_string())?;
    command
        .stdin(Stdio::null())
        .stdout(Stdio::from(log))
        .stderr(Stdio::from(log_err));

    // On Windows, a console subsystem child would flash a terminal window
    // every launch. CREATE_NO_WINDOW keeps the processes as invisible as a
    // service should be.
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }

    command.spawn().map_err(|e| e.to_string())
}

fn run_to_completion(mut command: Command, what: &str) -> Result<(), String> {
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
    let output = command
        .output()
        .map_err(|e| format!("{what}: couldn't run: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("{what}: {}", stderr.trim().chars().take(400).collect::<String>()));
    }
    Ok(())
}

/// Wait for something to accept a TCP connection. Readiness beyond this —
/// "does /ready say ready" — is the frontend's job, over HTTP, where the
/// policy for what counts lives.
fn wait_for_port(port: u16, timeout_secs: u64) -> bool {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    while std::time::Instant::now() < deadline {
        if std::net::TcpStream::connect(("127.0.0.1", port)).is_ok() {
            return true;
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
    }
    false
}

/// The hostname cloudflared prints for a quick tunnel, if this line has it.
///
/// cloudflared announces the assigned address in a box on stderr:
///
/// ```text
/// INF |  https://calm-river-1234.trycloudflare.com                           |
/// ```
///
/// No regex crate (see the module comment), so: the first `https://` on the
/// line, up to the next whitespace or box border, and it counts only if it is
/// a trycloudflare.com name. Anything else that starts with https:// on
/// cloudflared's stderr is documentation links in its startup banner.
fn quick_tunnel_url(line: &str) -> Option<String> {
    let start = line.find("https://")?;
    let rest = &line[start..];
    let end = rest
        .find(|c: char| c.is_whitespace() || c == '|' || c == '"')
        .unwrap_or(rest.len());
    let candidate = rest[..end].trim_end_matches('/');
    if candidate.ends_with(".trycloudflare.com") && candidate.len() > "https://.trycloudflare.com".len() {
        Some(candidate.to_string())
    } else {
        None
    }
}

/// Start a Cloudflare quick tunnel to the app and watch for its address.
///
/// Unlike every other component this one's stderr is *read*, not just
/// captured: the assigned hostname exists nowhere except in cloudflared's own
/// log output, and the app needs it at boot to mint invite links that name it.
/// A thread tees each line to tunnel.log — so the log stays as complete as
/// the other components' — and posts the first quick-tunnel URL it sees to
/// TUNNEL_URL.
///
/// `--no-autoupdate` because the binary is the bundle's to update, not
/// cloudflared's; a self-update would replace a file the installer owns.
fn spawn_tunnel(bundle: &Path, app_port: u16, log_path: &Path) -> Result<Child, String> {
    let binary = bundle.join(exe("cloudflared"));
    if !binary.exists() {
        return Err(
            "This installer's bundle has no cloudflared — a newer installer carries it. Until then, your server is reachable on your network only."
                .to_string(),
        );
    }

    let log = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(log_path)
        .map_err(|e| format!("couldn't open log {}: {e}", log_path.display()))?;
    let mut log_for_stderr = log.try_clone().map_err(|e| e.to_string())?;

    let mut command = Command::new(binary);
    command
        .arg("tunnel")
        .arg("--url")
        .arg(format!("http://127.0.0.1:{app_port}"))
        .arg("--no-autoupdate")
        .stdin(Stdio::null())
        .stdout(Stdio::from(log))
        .stderr(Stdio::piped());

    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }

    let mut child = command.spawn().map_err(|e| e.to_string())?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| "cloudflared started without a readable stderr".to_string())?;

    std::thread::spawn(move || {
        for line in BufReader::new(stderr).lines().map_while(Result::ok) {
            let _ = writeln!(log_for_stderr, "{line}");
            if let Some(url) = quick_tunnel_url(&line) {
                *TUNNEL_URL.lock().unwrap() = Some(url);
            }
        }
    });

    Ok(child)
}

/// Wait for the tunnel to report its address. Generous, because cloudflared
/// first has to reach Cloudflare's edge, and on a slow or captive network
/// that is the slowest thing in the whole start sequence. Late is fine — the
/// reader thread keeps listening and host_state will report the address when
/// it lands — but the app is about to be spawned with whatever is known now,
/// so a few extra seconds here buy correct invite links for the whole run.
fn wait_for_tunnel_url(timeout_secs: u64) -> Option<String> {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    while std::time::Instant::now() < deadline {
        if let Some(url) = TUNNEL_URL.lock().unwrap().clone() {
            return Some(url);
        }
        std::thread::sleep(std::time::Duration::from_millis(250));
    }
    None
}

// ------------------------------------------------------------------- options

fn options_path(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(data_dir(app)?.join("options.json"))
}

/// The persisted access choice, or None for an install that was never asked.
///
/// None is a real answer, not a default: it is what tells the frontend to put
/// the question in front of the person rather than silently exposing (or
/// silently not exposing) their server. An install from before v0.8 reads as
/// never-asked too, which is correct — nobody chose for it.
#[tauri::command]
pub async fn host_options_read(app: AppHandle) -> Result<Option<HostOptions>, String> {
    let path = options_path(&app)?;
    if !path.exists() {
        return Ok(None);
    }
    let text = std::fs::read_to_string(&path).map_err(|e| e.to_string())?;
    serde_json::from_str::<HostOptions>(&text)
        .map(Some)
        .map_err(|e| format!("options.json is unreadable: {e}"))
}

#[tauri::command]
pub async fn host_options_write(app: AppHandle, options: HostOptions) -> Result<(), String> {
    let path = options_path(&app)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let text = serde_json::to_string_pretty(&options).map_err(|e| e.to_string())?;
    std::fs::write(&path, text).map_err(|e| e.to_string())
}

/// Reveal the component logs in the OS file manager.
///
/// The panel used to tell people the path in prose — "under host/logs/" — and
/// stop there, because `open_external` refuses anything but http(s) and there
/// was nothing else to hand a folder to. Reading a log is the one thing a
/// person can do when a component fails, and a path they have to find by hand
/// is a path most never find.
#[tauri::command]
pub async fn host_open_logs(app: AppHandle) -> Result<(), String> {
    let logs = data_dir(&app)?.join("logs");
    std::fs::create_dir_all(&logs).map_err(|e| e.to_string())?;
    let mut command = if cfg!(windows) {
        let mut c = Command::new("explorer");
        c.arg(&logs);
        c
    } else if cfg!(target_os = "macos") {
        let mut c = Command::new("open");
        c.arg(&logs);
        c
    } else {
        let mut c = Command::new("xdg-open");
        c.arg(&logs);
        c
    };
    // Explorer in particular returns a non-zero status even on success, so the
    // spawn is the check, not the exit code.
    command
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map(|_| ())
        .map_err(|e| format!("couldn't open {}: {e}", logs.display()))
}

/// Remove everything the hosted server wrote: databases, homeserver state,
/// the IPFS repo, rendered configs, logs, and the access choice.
///
/// Stops the components first — Postgres through pg_ctl so it lets go of its
/// files — because deleting a live cluster's directory out from under it is
/// how you get a process that survives holding open handles to nothing.
/// Deliberately does NOT touch the keychain: the secrets are the frontend's,
/// stored by it and forgotten by it, and this module never held them.
///
/// The confirmation that this is wanted happens in the frontend, with the
/// words in front of the person. By the time this runs, they have said yes.
#[tauri::command]
pub async fn host_uninstall(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
) -> Result<(), String> {
    stop_all(&app, &processes);
    let data = data_dir(&app)?;
    if data.exists() {
        std::fs::remove_dir_all(&data)
            .map_err(|e| format!("couldn't remove {}: {e}", data.display()))?;
    }
    Ok(())
}

// ------------------------------------------------------------------- install

/// One-time setup: database cluster, homeserver identity, IPFS repo.
///
/// Steps are emitted by id as they begin; the labels live in
/// shared/hosting.ts INSTALL_STEPS, so what a person reads is tested policy
/// and what happens is this.
#[tauri::command]
pub async fn host_install(
    app: AppHandle,
    secrets: HostSecrets,
) -> Result<(), String> {
    if !bundle_present(&app) {
        return Err(
            "This build ships without server components — install a release build to host."
                .to_string(),
        );
    }
    if installed(&app) {
        return Ok(()); // Idempotent: an interrupted install can be retried.
    }

    let data = data_dir(&app)?;
    let logs = data.join("logs");

    emit_step(&app, "unpack");
    std::fs::create_dir_all(&logs).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(data.join("ipfs")).map_err(|e| e.to_string())?;

    // -- database ------------------------------------------------------------
    emit_step(&app, "database");

    // initdb reads the superuser password from a file, which exists for the
    // seconds initdb runs and is removed before anything else happens.
    let pwfile = data.join("pwfile");
    std::fs::write(&pwfile, &secrets.db_password).map_err(|e| e.to_string())?;

    let result = run_to_completion(
        {
            let mut c = Command::new(postgres_bin(&app, "initdb")?);
            c.arg("-D")
                .arg(data.join("pg"))
                .arg("-U")
                .arg("sovrgn")
                .arg("--auth=scram-sha-256")
                .arg("--pwfile")
                .arg(&pwfile)
                .arg("-E")
                .arg("UTF8");
            c
        },
        "initdb",
    );
    let _ = std::fs::remove_file(&pwfile);
    result?;

    // Unix sockets go in the data dir rather than /var/run, which needs no
    // privileges and exists on every platform that has sockets at all.
    let conf = data.join("pg").join("postgresql.conf");
    let mut extra = String::from("\n# SOVRGNnet hosted-server settings\nlisten_addresses = '127.0.0.1'\n");
    if !cfg!(windows) {
        extra.push_str(&format!(
            "unix_socket_directories = '{}'\n",
            data.join("pg").display()
        ));
    }
    std::fs::OpenOptions::new()
        .append(true)
        .open(&conf)
        .and_then(|mut f| f.write_all(extra.as_bytes()))
        .map_err(|e| format!("couldn't extend postgresql.conf: {e}"))?;

    // -- homeserver identity -------------------------------------------------
    emit_step(&app, "homeserver");

    // The signing key is this server's permanent identity on the Matrix
    // network. generate-keys ships alongside dendrite from the same build.
    run_to_completion(
        {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("generate-keys")));
            c.arg("--private-key")
                .arg(data.join("matrix_key.pem"));
            c
        },
        "generate-keys",
    )?;

    // -- file storage --------------------------------------------------------
    emit_step(&app, "storage");

    run_to_completion(
        {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("init").env("IPFS_PATH", data.join("ipfs"));
            c
        },
        "ipfs init",
    )?;

    // -- secrets -------------------------------------------------------------
    // Nothing to write: they came from the keychain via the frontend and go
    // into process environments at start. The step exists so the person sees
    // it happen rather than wondering what "keys" meant.
    emit_step(&app, "secrets");

    Ok(())
}

// --------------------------------------------------------------------- start

fn render_dendrite_config(
    app: &AppHandle,
    data: &Path,
    pg_port: u16,
    app_port: u16,
    secrets: &HostSecrets,
) -> Result<PathBuf, String> {
    let template_path = bundle_dir(app)?.join("dendrite.yaml.template");
    let template = std::fs::read_to_string(&template_path)
        .map_err(|e| format!("couldn't read dendrite template: {e}"))?;

    let database_url = format!(
        "postgresql://sovrgn:{}@127.0.0.1:{}/dendrite?sslmode=disable",
        secrets.db_password, pg_port
    );

    // Per-install, not the shared "sovrgn.host" this used to hardcode. Read
    // from the data dir so Dendrite and the app cannot disagree about it —
    // they would each produce different Matrix IDs for the same person.
    let server_name = matrix_server_name(data, &secrets.matrix_server_name)?;

    let rendered = template
        .replace("__MATRIX_SERVER_NAME__", &server_name)
        .replace("__MATRIX_SHARED_SECRET__", &secrets.matrix_shared_secret)
        .replace("__DENDRITE_DISABLE_FEDERATION__", "true")
        .replace("__DENDRITE_DATABASE_URL__", &database_url);

    // The same guard the install scripts apply: a placeholder that survives
    // rendering means the template grew a field this code doesn't know.
    for line in rendered.lines() {
        let code = line.trim_start();
        if !code.starts_with('#') && code.contains("__") && code.contains("__MATRIX") {
            return Err(format!("unfilled placeholder in dendrite template: {code}"));
        }
    }

    // The bundled template points private_key at /etc/dendrite; here it lives
    // in the data dir. Rewritten rather than templated so the production
    // template stays exactly what production uses.
    let rendered = rendered.replace(
        "/etc/dendrite/matrix_key.pem",
        &data.join("matrix_key.pem").display().to_string(),
    );

    // Same treatment for the storage paths, and this one was learned from a
    // corpse: the template's /var/lib/dendrite belongs to the systemd install
    // (StateDirectory) and to Docker (a root container writes /var/lib
    // freely). A desktop user cannot mkdir /var/lib/dendrite, and JetStream
    // said exactly that — level=fatal, first boot, every boot — while the
    // harness stayed green on the identical template. Windows quietly
    // tolerated it by creating \var\lib on the current drive, which is why
    // the Windows walk met a live homeserver and this Linux host never did.
    // Every /var/lib/dendrite path is rebased into the data dir; Dendrite
    // creates the subdirectories itself once their parent is writable.
    let rendered = rendered.replace(
        "/var/lib/dendrite",
        &data.join("dendrite").display().to_string(),
    );

    // Dendrite's Windows build fatals on the template's `std` logging hook —
    // log_windows.go recognises only `file` — so the very first Windows boot
    // died in SetupHookLogging before binding a port, and the panel read
    // "starting" forever. The hook is redundant on a desktop host anyway:
    // dendrite logs to stderr unconditionally, and the supervisor captures
    // stderr into dendrite.log on every platform. Dropped everywhere rather
    // than cfg-gated so Linux and Windows render the same config; the
    // production template keeps its hook, same policy as the path rewrites
    // above.
    let rendered = rendered.replace("logging:\n  - type: std\n    level: info", "logging: []");
    if rendered.contains("type: std") {
        // Same guard as the placeholders: a hook that survives rewriting
        // means the template changed shape and this code no longer knows it.
        return Err("dendrite template's std logging hook survived rewriting".to_string());
    }

    // The appservice registration (ADR 0015) — rendered beside the config
    // from the bundle's template, with this start's tokens and this start's
    // app port, and the template's /etc/dendrite path rebased into the data
    // dir exactly as the signing key's is. Dendrite reads it at boot, which
    // is why the app's port has to be known before Dendrite starts, and why
    // the caller picks it early.
    let registration = render_appservice_registration(app, data, app_port, secrets)?;
    let rendered = rendered.replace(
        "/etc/dendrite/appservice.yaml",
        &registration.display().to_string(),
    );
    if rendered.contains("/etc/dendrite/appservice.yaml") || !rendered.contains("app_service_api:") {
        // Same guard as the placeholders: a template that no longer lists the
        // registration would start a homeserver that never tells the instance
        // anything, and every client-authored event would vanish silently.
        return Err("dendrite template's app_service_api section is missing or unrewritten".to_string());
    }

    // The listen port is a CLI flag at spawn, not a config field — the port
    // is picked fresh each start and the config shouldn't pretend otherwise.
    let path = data.join("dendrite.yaml");
    std::fs::write(&path, rendered).map_err(|e| e.to_string())?;
    Ok(path)
}

/// The registration file Dendrite reads to know where to push events, and
/// under which token. Written each start: the app's port is chosen fresh
/// each start, and the file names it.
fn render_appservice_registration(
    app: &AppHandle,
    data: &Path,
    app_port: u16,
    secrets: &HostSecrets,
) -> Result<PathBuf, String> {
    if secrets.appservice_as_token.is_empty() || secrets.appservice_hs_token.is_empty() {
        return Err("the appservice tokens are missing from this install's secrets".to_string());
    }
    let template_path = bundle_dir(app)?.join("appservice.yaml.template");
    let template = std::fs::read_to_string(&template_path).map_err(|e| {
        format!(
            "couldn't read appservice template: {e} — this installer's bundle predates always-on encryption; install a newer one"
        )
    })?;
    let rendered = template
        .replace("{{AS_TOKEN}}", &secrets.appservice_as_token)
        .replace("{{HS_TOKEN}}", &secrets.appservice_hs_token)
        .replace("{{APP_URL}}", &format!("http://127.0.0.1:{app_port}"));
    for line in rendered.lines() {
        let code = line.trim_start();
        if !code.starts_with('#') && code.contains("{{") {
            return Err(format!("unfilled placeholder in appservice template: {code}"));
        }
    }
    let path = data.join("appservice.yaml");
    std::fs::write(&path, rendered).map_err(|e| e.to_string())?;
    Ok(path)
}

/// LiveKit reads its ports and keys from a config file — its own format,
/// like dendrite.yaml, which is the one place secrets are allowed to touch
/// disk. Rendered fresh each start because the port is picked fresh each
/// start.
///
/// Two addresses in here are deliberate. `bind_addresses` is 0.0.0.0 because
/// voice is the one component that must NOT live on loopback: the media has
/// to be dialable by the people on the LAN the server claims to serve.
/// `use_external_ip` is false because a desktop host is a LAN machine — the
/// SFU should advertise the interfaces it actually has, not ask a STUN
/// server for a public address nobody forwarded.
fn render_livekit_config(
    data: &Path,
    port: u16,
    udp: (u16, u16),
    secrets: &HostSecrets,
) -> Result<PathBuf, String> {
    let (udp_start, udp_end) = udp;
    let tcp_port = port + 1; // ICE/TCP fallback beside the ws port — the kubo gateway precedent
    let rendered = format!(
        "# Written by the desktop supervisor each start — hosting.rs.\n\
         port: {port}\n\
         bind_addresses:\n\
         \x20 - \"0.0.0.0\"\n\
         rtc:\n\
         \x20 port_range_start: {udp_start}\n\
         \x20 port_range_end: {udp_end}\n\
         \x20 tcp_port: {tcp_port}\n\
         \x20 use_external_ip: false\n\
         keys:\n\
         \x20 \"{key}\": \"{secret}\"\n",
        key = secrets.livekit_api_key,
        secret = secrets.livekit_api_secret,
    );
    let path = data.join("livekit.yaml");
    std::fs::write(&path, rendered).map_err(|e| e.to_string())?;
    Ok(path)
}

/// Start every component. Returns the final report; the same report is also
/// emitted as an event so the UI can render without racing the invoke.
#[tauri::command]
pub async fn host_start(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
    secrets: HostSecrets,
    ports: PortPlan,
    options: HostOptions,
) -> Result<HostReport, String> {
    if !installed(&app) {
        return Err("Nothing is installed to start.".to_string());
    }
    // A start is a fresh tunnel or no tunnel; either way, last run's address
    // is not this run's.
    *TUNNEL_URL.lock().unwrap() = None;

    let data = data_dir(&app)?;
    let logs = data.join("logs");
    std::fs::create_dir_all(&logs).map_err(|e| e.to_string())?;

    let mut components: Vec<ComponentReport> = Vec::new();
    let fail = |components: &mut Vec<ComponentReport>, id: &str, error: String| {
        components.push(ComponentReport {
            id: id.to_string(),
            state: "failed".to_string(),
            port: None,
            error: Some(error),
        });
    };

    // -- postgres ------------------------------------------------------------
    let pg_port = pick_port(&ports.postgres)?;
    {
        let mut c = Command::new(postgres_bin(&app, "postgres")?);
        c.arg("-D")
            .arg(data.join("pg"))
            .arg("-p")
            .arg(pg_port.to_string());
        match spawn_logged(c, &logs.join("postgres.log")) {
            Ok(child) => {
                processes.0.lock().unwrap().insert("postgres".into(), child);
                if wait_for_port(pg_port, 30) {
                    components.push(ComponentReport {
                        id: "postgres".into(),
                        state: "running".into(),
                        port: Some(pg_port),
                        error: None,
                    });
                } else {
                    fail(&mut components, "postgres", "didn't accept connections within 30s".into());
                }
            }
            Err(e) => fail(&mut components, "postgres", e),
        }
    }

    // The two databases, created if they don't exist.
    //
    // Not `createdb`. zonky's embedded-postgres binaries — plain PostgreSQL
    // repackaged per platform, which is what the bundle ships — omit the
    // client tools on Windows and Linux and include them on macOS. A bundle
    // built on a Mac therefore worked, shipped, and failed on a user's Windows
    // machine three steps into a first run with "The system cannot find the
    // file specified": a missing file nobody would think to look for, because
    // it was present when the bundle was built.
    //
    // `createdb` is a thin wrapper around `CREATE DATABASE`. Doing it over a
    // connection removes the dependency instead of working around it, and the
    // bundle already carries both Node and the postgres driver. Both databases
    // in one call, and it exits 0 when they already exist — the ordinary
    // second launch is not an error.
    if components.iter().any(|c| c.id == "postgres" && c.state == "running") {
        let bundle = bundle_dir(&app)?;
        let mut c = Command::new(bundle.join(exe("node")));
        c.arg(bundle.join("app").join("createdbs.mjs"))
            .arg("sovrgnnet")
            .arg("dendrite")
            .env("PGHOST", "127.0.0.1")
            .env("PGPORT", pg_port.to_string())
            .env("PGUSER", "sovrgn")
            .env("PGPASSWORD", &secrets.db_password);
        run_to_completion(c, "create databases")?;
    }

    // The app's port, chosen here rather than beside the app, because the
    // appservice registration Dendrite reads at boot names it (ADR 0015).
    // Bind-and-release like every pick; the window between this and the
    // app's spawn is a few components long, and the same race already
    // existed between each pick and its own spawn.
    let app_port = pick_port(&ports.app)?;

    // -- dendrite ------------------------------------------------------------
    let matrix_port = pick_port(&ports.matrix)?;
    match render_dendrite_config(&app, &data, pg_port, app_port, &secrets) {
        Ok(config) => {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("dendrite")));
            c.arg("--config")
                .arg(&config)
                .arg("--http-bind-address")
                .arg(format!("127.0.0.1:{matrix_port}"));
            match spawn_logged(c, &logs.join("dendrite.log")) {
                Ok(child) => {
                    processes.0.lock().unwrap().insert("matrix".into(), child);
                    components.push(ComponentReport {
                        id: "matrix".into(),
                        state: if wait_for_port(matrix_port, 60) { "running" } else { "starting" }.into(),
                        port: Some(matrix_port),
                        error: None,
                    });
                }
                Err(e) => fail(&mut components, "matrix", e),
            }
        }
        Err(e) => fail(&mut components, "matrix", e),
    }

    // -- kubo ----------------------------------------------------------------
    let ipfs_port = pick_port(&ports.ipfs)?;
    {
        // The repo's addresses are rewritten each start, because the port is
        // picked each start. Kubo reads them from its config, not flags.
        for (key, value) in [
            ("Addresses.API", format!("\"/ip4/127.0.0.1/tcp/{ipfs_port}\"")),
            ("Addresses.Gateway", format!("\"/ip4/127.0.0.1/tcp/{}\"", ipfs_port + 1)),
        ] {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("config").arg("--json").arg(key).arg(&value).env("IPFS_PATH", data.join("ipfs"));
            if let Err(e) = run_to_completion(c, &format!("ipfs config {key}")) {
                fail(&mut components, "ipfs", e);
                break;
            }
        }
        if !components.iter().any(|c| c.id == "ipfs") {
            let mut c = Command::new(bundle_dir(&app)?.join(exe("kubo")));
            c.arg("daemon").env("IPFS_PATH", data.join("ipfs"));
            match spawn_logged(c, &logs.join("ipfs.log")) {
                Ok(child) => {
                    processes.0.lock().unwrap().insert("ipfs".into(), child);
                    components.push(ComponentReport {
                        id: "ipfs".into(),
                        state: "starting".into(), // fine to be late; chat doesn't wait for files
                        port: Some(ipfs_port),
                        error: None,
                    });
                }
                Err(e) => fail(&mut components, "ipfs", e),
            }
        }
    }

    // -- livekit (voice) -----------------------------------------------------
    // What makes `voice: true` true on a desktop-hosted instance — ADR 0013
    // as superseded: every instance houses its own voice backend, and a
    // laptop is an instance. Deliberately optional twice over: an older
    // bundle has no binary, an older keychain (not yet backfilled by the
    // frontend) has no keys, and either way the app below simply never
    // receives LIVEKIT_* — the instance advertises voice: false rather than
    // failing, exactly the posture a dedicated deployment takes when its
    // operator hasn't set the three env lines.
    //
    // Skipping is a state, not an absence. The first version of this block
    // pushed nothing when the gate didn't pass, and the first real walk of
    // the voice release probed a machine and found three silences — no
    // process, no config, no log — with nothing anywhere saying whether
    // voice had been skipped, had crashed, or had never been reached. A
    // person cannot tell "off on purpose" from "broken" unless the
    // supervisor says which, so it says which: an "off" row with the reason
    // in words, held in VOICE_OFF_REASON so host_state polls (which rebuild
    // from live processes) keep saying it.
    //
    // Reported as "starting" without waiting, the kubo reasoning: chat
    // doesn't wait for voice, and the next host_state poll tells the truth.
    let mut voice_port: Option<u16> = None;
    {
        let livekit = bundle_dir(&app)?.join(exe("livekit"));
        let have_binary = livekit.exists();
        let have_keys = !secrets.livekit_api_key.is_empty()
            && !secrets.livekit_api_secret.is_empty();
        *VOICE_OFF_REASON.lock().unwrap() = None;
        if have_binary && have_keys {
            match pick_port(&ports.voice) {
                Ok(port) => match render_livekit_config(&data, port, ports.voice_udp, &secrets) {
                    Ok(config) => {
                        let mut c = Command::new(&livekit);
                        c.arg("--config").arg(&config);
                        match spawn_logged(c, &logs.join("livekit.log")) {
                            Ok(child) => {
                                processes.0.lock().unwrap().insert("voice".into(), child);
                                voice_port = Some(port);
                                components.push(ComponentReport {
                                    id: "voice".into(),
                                    state: "starting".into(),
                                    port: Some(port),
                                    error: None,
                                });
                            }
                            Err(e) => fail(&mut components, "voice", e),
                        }
                    }
                    Err(e) => fail(&mut components, "voice", e),
                },
                Err(e) => fail(&mut components, "voice", e),
            }
        } else {
            let reason = if !have_binary {
                // Only release bundles carry the SFU; a bundle assembled
                // before the voice release simply doesn't have the file.
                "this bundle carries no voice server — chat is unaffected"
            } else {
                // hostSecrets() backfills the pair before every start, so an
                // empty key here means the keychain refused to hand it over.
                "no voice signing pair — the keychain didn't provide one at start"
            };
            *VOICE_OFF_REASON.lock().unwrap() = Some(reason.to_string());
            components.push(ComponentReport {
                id: "voice".into(),
                state: "off".into(),
                port: None,
                error: Some(reason.to_string()),
            });
        }
    }

    // -- tunnel --------------------------------------------------------------
    //
    // Before the app, for the reason shared/hosting.ts gives beside voice:
    // the app reads its public hostname from the environment at boot, and a
    // quick tunnel's hostname exists only once cloudflared has connected.
    // cloudflared is content to come up before its origin does — it answers
    // 502 until the app is listening, then stops — so the ordering costs
    // nothing but the wait.
    let mut public_url: Option<String> = None;
    if options.wants_tunnel() {
        match spawn_tunnel(&bundle_dir(&app)?, app_port, &logs.join("tunnel.log")) {
            Ok(child) => {
                processes.0.lock().unwrap().insert("tunnel".into(), child);
                public_url = wait_for_tunnel_url(30);
                components.push(ComponentReport {
                    id: "tunnel".into(),
                    state: if public_url.is_some() { "running" } else { "starting" }.into(),
                    port: None,
                    error: None,
                });
            }
            Err(e) => fail(&mut components, "tunnel", e),
        }
    }

    // -- app -----------------------------------------------------------------
    {
        let bundle = bundle_dir(&app)?;
        let mut c = Command::new(bundle.join(exe("node")));
        c.arg(bundle.join("app").join("index.mjs"))
            .current_dir(bundle.join("app"))
            .env("NODE_ENV", "production")
            .env("PORT", app_port.to_string())
            .env(
                "DATABASE_URL",
                format!(
                    "postgresql://sovrgn:{}@127.0.0.1:{}/sovrgnnet",
                    secrets.db_password, pg_port
                ),
            )
            .env("JWT_SECRET", &secrets.jwt_secret)
            .env("MATRIX_SHARED_SECRET", &secrets.matrix_shared_secret)
            // Same value Dendrite was rendered with, from the same file. If
            // these two ever diverge, the app mints @alice:a while the
            // homeserver only knows @alice:b, and every login fails with
            // M_FORBIDDEN saying nothing about why.
            .env("MATRIX_SERVER_NAME", &matrix_server_name(&data, &secrets.matrix_server_name)?)
            .env("MATRIX_HOMESERVER_URL", format!("http://127.0.0.1:{matrix_port}"))
            .env("IPFS_API_URL", format!("http://127.0.0.1:{ipfs_port}"))
            .env("SOVRGN_SETUP_TOKEN", &secrets.setup_token)
            // The same two values Dendrite's registration was rendered with
            // (ADR 0015). If these ever diverge, every push the homeserver
            // makes is a 403 in app.log and an index that silently stops
            // following the rooms it is supposed to mirror.
            .env("MATRIX_APPSERVICE_AS_TOKEN", &secrets.appservice_as_token)
            .env("MATRIX_APPSERVICE_HS_TOKEN", &secrets.appservice_hs_token)
            .env("INSTANCE_NAME", "My computer")
            .env("INSTANCE_JOIN_POLICY", "invite")
            .env("SOVRGNNET_ACCESS_MODE", if options.wants_tunnel() { "tunnel" } else { "lan" });
        // The one address that is right for everyone, handed to the app so
        // invite links name it instead of the owner's loopback
        // (server/lanHost.ts). Only when known: an app started with a stale
        // or guessed public host would mint links to nowhere with total
        // confidence, which is worse than LAN links that at least say where
        // they point.
        if let Some(url) = &public_url {
            c.env("SOVRGN_PUBLIC_HOST", url);
        }
        // Only when the SFU actually started: these three are the exact
        // switch behind the instance's `voice` capability flag, and setting
        // them beside a component that failed to spawn would advertise a
        // capability that isn't there. Loopback is correct here — the server
        // substitutes the caller's own host at voice.join, the invite-link
        // treatment (server/lanHost.ts).
        if let Some(port) = voice_port {
            c.env("LIVEKIT_URL", format!("ws://127.0.0.1:{port}"))
                .env("LIVEKIT_API_KEY", &secrets.livekit_api_key)
                .env("LIVEKIT_API_SECRET", &secrets.livekit_api_secret);
        }
        // First boot applies migrations; the step is announced so the pause
        // reads as work rather than a hang.
        emit_step(&app, "migrate");
        match spawn_logged(c, &logs.join("app.log")) {
            Ok(child) => {
                emit_step(&app, "start");
                processes.0.lock().unwrap().insert("app".into(), child);
                components.push(ComponentReport {
                    id: "app".into(),
                    state: if wait_for_port(app_port, 90) { "running" } else { "starting" }.into(),
                    port: Some(app_port),
                    error: None,
                });
            }
            Err(e) => fail(&mut components, "app", e),
        }
    }

    let url = components
        .iter()
        .find(|c| c.id == "app" && c.state == "running")
        .and_then(|c| c.port)
        .map(|p| format!("http://127.0.0.1:{p}"));

    let report = HostReport {
        installed: true,
        components,
        url,
        public_url,
    };
    emit_state(&app, &report);
    Ok(report)
}

// ---------------------------------------------------------------------- stop

/// Stop everything, most-dependent first. Postgres goes through pg_ctl so it
/// checkpoints instead of recovering on next start; the single-process Go and
/// Node components are killed, which their databases are built to survive.
#[tauri::command]
pub async fn host_stop(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
) -> Result<(), String> {
    stop_all(&app, &processes);
    Ok(())
}

pub fn stop_all(app: &AppHandle, processes: &HostProcesses) {
    // A stopped server has no voice row to explain. The reason belongs to a
    // running-but-voiceless host; leaving it set would make host_state report
    // an "off" SFU for a server that is entirely off.
    *VOICE_OFF_REASON.lock().unwrap() = None;
    *TUNNEL_URL.lock().unwrap() = None;

    let mut map = processes.0.lock().unwrap();

    // The tunnel goes first: it is the only component with a public face, and
    // a public address that answers 502 for the seconds the app takes to die
    // is a worse last impression than one that simply stops resolving.
    for id in ["tunnel", "app", "voice", "ipfs", "matrix"] {
        if let Some(mut child) = map.remove(id) {
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    if let Some(mut child) = map.remove("postgres") {
        let stopped = data_dir(app)
            .and_then(|data| {
                run_to_completion(
                    {
                        let mut c = Command::new(postgres_bin(app, "pg_ctl")?);
                        c.arg("stop").arg("-D").arg(data.join("pg")).arg("-m").arg("fast");
                        c
                    },
                    "pg_ctl stop",
                )
            })
            .is_ok();
        if !stopped {
            let _ = child.kill();
        }
        let _ = child.wait();
    }
}

// --------------------------------------------------------------------- state

/// The current picture: what's installed, what's running, what died.
///
/// A child that exited is reported as failed with whatever exit status it
/// left, which is how the frontend learns about a crash between polls.
#[tauri::command]
pub async fn host_state(
    app: AppHandle,
    processes: tauri::State<'_, HostProcesses>,
) -> Result<HostReport, String> {
    let mut components = Vec::new();
    let mut map = processes.0.lock().unwrap();

    let public_url = TUNNEL_URL.lock().unwrap().clone();

    for (id, child) in map.iter_mut() {
        let state = match child.try_wait() {
            // Alive is running — except for the tunnel, which is alive from
            // the moment it spawns and *useful* only once it has an address.
            // Reporting the gap as "starting" is what lets the panel show a
            // spinner beside "public link" instead of a green dot beside
            // nothing.
            Ok(None) if id == "tunnel" && public_url.is_none() => ("starting".to_string(), None),
            Ok(None) => ("running".to_string(), None),
            Ok(Some(status)) => ("failed".to_string(), Some(format!("exited: {status}"))),
            Err(e) => ("failed".to_string(), Some(e.to_string())),
        };
        components.push(ComponentReport {
            id: id.clone(),
            state: state.0,
            port: None,
            error: state.1,
        });
    }

    // A deliberately-off SFU has no child to poll; keep saying why it's off,
    // or the panel's voice row exists for one report and then evaporates.
    if let Some(reason) = VOICE_OFF_REASON.lock().unwrap().clone() {
        components.push(ComponentReport {
            id: "voice".into(),
            state: "off".into(),
            port: None,
            error: Some(reason),
        });
    }

    Ok(HostReport {
        installed: installed(&app),
        components,
        url: None,
        public_url,
    })
}

/// Whether this build can host at all, and whether it already does.
#[tauri::command]
pub async fn host_available(app: AppHandle) -> Result<serde_json::Value, String> {
    Ok(serde_json::json!({
        "bundled": bundle_present(&app),
        "installed": installed(&app),
    }))
}

// ---------------------------------------------------------------------- tests

#[cfg(test)]
mod tests {
    use super::*;

    // The only piece of this module with logic worth a unit test that
    // doesn't need a process: the line scanner that finds cloudflared's
    // assigned hostname. Everything else here is spawning and waiting.

    #[test]
    fn finds_the_quick_tunnel_url_in_cloudflareds_box() {
        // Verbatim shape of what cloudflared prints, timestamp and all.
        let line = "2026-09-08T05:12:33Z INF |  https://calm-river-1234.trycloudflare.com                                     |";
        assert_eq!(
            quick_tunnel_url(line).as_deref(),
            Some("https://calm-river-1234.trycloudflare.com")
        );
    }

    #[test]
    fn ignores_the_documentation_links_in_the_banner() {
        // cloudflared's startup banner has https:// links of its own, none
        // of which are the tunnel.
        for line in [
            "INF Requesting new quick Tunnel on trycloudflare.com...",
            "INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |",
            "INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment. https://developers.cloudflare.com/cloudflare-one/",
            "WRN Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]",
        ] {
            assert_eq!(quick_tunnel_url(line), None, "matched: {line}");
        }
    }

    #[test]
    fn stops_at_whitespace_borders_and_quotes() {
        assert_eq!(
            quick_tunnel_url("x https://a-b.trycloudflare.com| y").as_deref(),
            Some("https://a-b.trycloudflare.com")
        );
        assert_eq!(
            quick_tunnel_url("url=\"https://a-b.trycloudflare.com\"").as_deref(),
            Some("https://a-b.trycloudflare.com")
        );
        assert_eq!(
            quick_tunnel_url("https://a-b.trycloudflare.com/").as_deref(),
            Some("https://a-b.trycloudflare.com")
        );
    }

    #[test]
    fn refuses_a_bare_domain_and_other_hosts() {
        // A suffix match alone would accept the empty-subdomain form, which
        // cloudflared never assigns and which a person could not dial.
        assert_eq!(quick_tunnel_url("https://.trycloudflare.com"), None);
        assert_eq!(quick_tunnel_url("https://example.com"), None);
        assert_eq!(quick_tunnel_url("http://a-b.trycloudflare.com"), None);
    }

    #[test]
    fn options_round_trip_and_tolerate_the_unknown() {
        let json = serde_json::to_string(&HostOptions { access: "tunnel".into() }).unwrap();
        let back: HostOptions = serde_json::from_str(&json).unwrap();
        assert!(back.wants_tunnel());
        // A value from a newer frontend still parses, and reads as no tunnel.
        let future: HostOptions = serde_json::from_str(r#"{"access":"something-new"}"#).unwrap();
        assert!(!future.wants_tunnel());
        let lan: HostOptions = serde_json::from_str(r#"{"access":"lan"}"#).unwrap();
        assert!(!lan.wants_tunnel());
    }
}
